### ISSUE TITLE
Hello, I have a question as shown in the picture. How can I solve this problem？

### ISSUE THREAD

**Issue by AdorableDevil** [ehgh/PARSRec-Explainable-Personalized-Attention-fused-Recurrent-Sequential-Recommendation#2]
![1](https://github.com/ehgh/PARSRec-Explainable-Personalized-Attention-fused-Recurrent-Sequential-Recommendation/assets/61314380/4f0352c3-9d53-4ca2-acfd-ffc3725d88cd)
Thank you very much

**Comment by ehgh** [comment]
Hi, Could you please provide a bit more detail to help us debug the issue?
For e.g.
- What command results in this error?
- Are contents of file `PARSRec.sh` or `synthetic_data_generator.sh` modified?
- Is the synthetic data generated via `./synthetic_data_generator.sh` command before running the code above?
Thank you.

**Comment by ehgh** [comment]
Hi, Could you please provide a bit more detail to help us debug the issue?
For e.g.

What command results in this error?
Are contents of file `PARSRec.sh` or `synthetic_data_generator.sh` modified?
Is the synthetic data generated via `./synthetic_data_generator.sh` command before running the code above?
Thank you.

**Comment by AdorableDevil** [comment]
I have solved this problem, it was my slight mistake that I did not configure the environment properly. Thank you very much. We will have more communication and exchange ideas when having time!

**Comment by ehgh** [comment]
Glad to hear it is resolved. Closing this issue. Please feel free to open a new issue if you have any questions.

**Comment by ehgh** [comment]
Glad to hear it is resolved. Closing this issue. Please feel free to open a new issue if you have any questions.
